### ISSUE TITLE
Parsing Name Error -- Wrong Last Name

### ISSUE THREAD

**Issue by lexvisio** [ADCI/full-name-parser#1]
Odd one. The full name string "John J Oliveri" returns first name "John", middle name "J Ol" and lastname "eri"
I have tested it running through over a thousand names, this is the only serious error I have experienced.

I have looked at the ascii values to ensure the spaces and characters are normal values.
Testing running php7.2.0, Debian sid, and the newest release of full-name-parser.

**Comment by Deyter** [comment]
@lexvisio Thank you for the issue.
There was a bug with suffixes and prefixes parsing.
It was fixed in [release 0.1.1.](https://github.com/ADCI/full-name-parser/releases/tag/0.1.1)
