### ISSUE TITLE
Exception if source name contains multiple initials. ADCI\FullNameParser\Exception\NameParsingException: The regex being used has multiple matches. in ADCI\FullNameParser\Parser->removeTokenWithRegex()

### ISSUE THREAD

**Issue by anton87gp** [ADCI/full-name-parser#2]
The error does not occur when the second initial from the third author's name is removed: "Villuendas, M. V." -> "Villuendas, M.".

Issue originally appeared in use with drupal/bibcite module: https://www.drupal.org/project/bibcite/issues/2945406

**Comment by Deyter** [comment]
@anton87gp There was a bug with parsing suffixes which contain trailing dots.
Also, we added the separated list for numeral suffixes without trailing dots.
It makes for separate `V.` like middle name initial in the example above and `V` like `the fifth`.
If you don't need this logic you can override suffixes and numeral suffixes lists. Example of overriding lists contains in the readme file and on [main page of the project](https://github.com/ADCI/full-name-parser).
All it in release 0.2.0.
