### ISSUE TITLE
Comparison with Python nameparser

### ISSUE THREAD

**Issue by robertandrews** [ADCI/full-name-parser#3]
How similar is this to the Python [nameparser](https://pypi.python.org/pypi/nameparser/0.2.7) [module](https://github.com/derek73/python-nameparser)?

I have previously found pretty good results with it on a set of 4,000+ names, many of which are international.

But I am now looking at moving the same process to PHP, and would like to find similar parsing results.

**Comment by Deyter** [comment]
@robertandrews 
This parser looks similar to other parsers.
I've found some small differences between this [Python nameparser module](https://github.com/derek73/python-nameparser) and our.
1. We don't fix case of `Mac` lastname part. In `MacDonald` name for example.
2. We don't make conjunctions of leading title. But you can set compound titles in options.
3. There are some additional functions in python parser. Like return name in the requested format. Maybe we will implement some of them in future versions.

We do not see major differences in parsing algorithms, but we cannot say that we tested a lot of international names. So, please test on your set of names and check results carefully. And feel free to post new issues and feature requests.

**Comment by robertandrews** [comment]
> please test on your set of names and check results carefully. And feel free to post new issues and feature requests.

I will. Thanks.
