### ISSUE TITLE
Running on PHP pre-5.6

### ISSUE THREAD

**Issue by robertandrews** [ADCI/full-name-parser#4]
Two installation issues:

1.
During `composer require adci/full-name-parser`, composer returns:

`[InvalidArgumentException]
Could not find package adci/full-name-parser at any version matching your PHP version 5.5.34.0`

Does this work with my PHP version? Can I use `--ignore-platform-reqs` to override?

2.
Does it create vendor/autoload.php?
Do I need to specify `require 'vendor/autoload.php'` in my code?

Thanks.

**Comment by robertandrews** [comment]
Using `composer require adci/full-name-parser --ignore-platform-reqs` produces the same message:

`[InvalidArgumentException] Could not find package adci/full-name-parser at any version matching your PHP version 5.5.34.0`

**Comment by robertandrews** [comment]
Composer does not return this sort of message...

`This package requires php >=5.6 but your PHP version (5.5.34) does not satisfy that requirement.`

**Comment by Deyter** [comment]
@robertandrews 
Thanks for your questions.
1.  I recommend setting [platform](https://getcomposer.org/doc/06-config.md#platform) option in `composer.json` file. As it is said in the documentation this option
> Lets you fake platform packages (PHP and extensions)

The parser may work with PHP <  5.6 version but this wasn't tested enough, so we cannot guarantee that parser will work 100% correctly on these versions. And we're not going to add such support, basically, there is no reason to support legacy versions.

2. Yes, Composer will create `vendor/autoload.php` automatically and you need to attach it to your code by `require_once`. If you use some sort of CMS or framework it could be done in its core code already.

**Comment by robertandrews** [comment]
Re: 1

> The parser may work with PHP < 5.6 version but this wasn't tested enough, so we cannot guarantee that parser will work 100% correctly on these versions. And we're not going to add such support, basically, there is no reason to support legacy versions.

I aim to use EasyApache4/ManagePHP to allow me to switch to a newer version of PHP.

Thanks.
