### ISSUE TITLE
Exception when parsing a name with multiple last names.

### ISSUE THREAD

**Issue by lmendes79** [ADCI/full-name-parser#8]
Hello! I got an exception when parsing a name a name with multiple last names: "Arantes Rodrigues, R". From what I could trace it goes to Parser::findExtraSuffix("R"), Parser::removeTokenWithRegex("/(R)/"), where it tries to remove all "R" from the string, resulting in more than one match, throwing the exception.

**Comment by Deyter** [comment]
@lmendes79 
Thanks for your issue. Fixes is near committed state right now.
But we need to review some other small changes to make name parser better.
The new version of parser will be released in nearest time.

**Comment by Deyter** [comment]
@lmendes79
We released [version 0.2.1](https://github.com/ADCI/full-name-parser/releases/tag/0.2.1)
There was fixed this issue exception.
Also, we made some inner changes(for future versions), add more inherit name parsing exception types to make easier diagnostic parsing problems for users or handle it if need and make more code coverage by tests.

**Comment by lmendes79** [comment]
Great !! Thank you @Deyter !!
