### ISSUE TITLE
Error Parsing Name

### ISSUE THREAD

**Issue by smccoy78** [ADCI/full-name-parser#9]
I have a name that consists of first name, middle initial, last name and suffix.

For example: John A Smith DDS

When parsed it returns as such:
fullName: "John A Smith DDS"
leadingInitial: null
firstName: "John"
nicknames: null
middleName: "A Smith"
lastName: "DDS"
academicTitle: null
suffix: null
errors: []

**Comment by Deyter** [comment]
@smccoy78 It is unknown suffix for parser and me. If you add it to the list it will be parsed correctly.
Something like that.
```php
<?php
use ADCI\FullNameParser\Parser;
// Some code...
$parser = new Parser(['suffixes' => 'DDS, esq, jr, sr, phd', 'part' => 'all', 'fix_case' => TRUE]); 
```

We cannot set list of full suffixes because it is different for different work area.
